[package]
name = "nb-search"
version = "0.1.0"
authors = ["Piyush Rungta <piyushrungta25@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32"
walkdir = "2"
serde_json = "~1"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
termcolor = "1"

[[bin]]
path = "src/main.rs"
name = "nbs"